version: "3.8"


services:
  management:
    build: .
    depends_on:
      - postgis
    env_file: .env
#    ports:
#      - 8888:8888
    volumes:
      - .:/app

  postgis:
    image: postgis/postgis:14-3.2-alpine
    env_file: .env
#    ports:
#      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
